spring:
  application:
    name: domaindns-backend
  profiles:
#    active: prod
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:}
    password: ${MAIL_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 587
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:}
      database: ${REDIS_DB:0}
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
server:
  port: 8080

jwt:
  secret: "replace-with-strong-secret"
  issuer: "domaindns"
  expire-minutes: 1440

secrets:
  aes-key: ${SECRETS_AES_KEY:}

github:
  token: ${GITHUB_TOKEN:}

aliyun:
  api:
    appcode: ${ALIYUN_API_APPCODE:}